### ISSUE TITLE
NOT UPDATE ANYMORE?

### ISSUE THREAD

**Issue by azmifxuzychess** [jetkai/proxy-list#10]
Hey, why proxies is not updating anymore?

**Comment by jetkai** [comment]
@azmifxuzychess I have restarted the server but the GH security token may have expired. I'll look into it tonight.

**Comment by jetkai** [comment]
Proxy sources will be updated by the end of this month. This will bring more unique proxies to the list.

Issue with list automatically updating has been fixed 3 weeks ago.
