### ISSUE TITLE
Remove Ports

### ISSUE THREAD

**Issue by KingKrex69** [jetkai/proxy-list#12]
Create clone of the repository or create clone of the 2 folders bit without the ports after the proxy ip
for example remove the port from the proxy but put it into another folder

**Comment by st0x0ne** [comment]
What purpose would this serve...?

**Comment by KingKrex69** [comment]
> What purpose would this serve...?

Easier usage for BotNets

**Comment by st0x0ne** [comment]
> > What purpose would this serve...?
> 
> Easier usage for BotNets

lol

**Comment by jetkai** [comment]
@KingKrex69 - You should be able to do this with a bash, powershell or terminal command to automate that process. This project just has lists of working proxies in different file formats. 😊
