### ISSUE TITLE
china proxies

### ISSUE THREAD

**Issue by andress134** [jetkai/proxy-list#3]
hello sir @jetkai 
You can made also china.txt with just china proxies?
http://www.xiladaili.com/http/  http://www.nimadaili.com/http/  here is a source with good china proxies
Also the project is updated automaticaly? will it run for long time ?

**Comment by jetkai** [comment]
> hello sir @jetkai 
> 
> You can made also china.txt with just china proxies?
> 
> http://www.xiladaili.com/http/  http://www.nimadaili.com/http/  here is a source with good china proxies
> 
> Also the project is updated automaticaly? will it run for long time ?

Hi @andress134 !

I am currently working on an update that'll have the geo locations for each proxy. This includes China which you will be able to request from a text file.

It'll probably be a couple of weeks though :)

**Comment by jetkai** [comment]
@andress134 I have added the country & regions to the proxies if you're still interested. It's not in .txt files at the moment, but it is available in json, yaml, xml & csv. 😊
