### ISSUE TITLE
Zero proxies for a while

### ISSUE THREAD

**Issue by alextatarinov** [jetkai/proxy-list#7]
Probably something has broken on the background

**Comment by jetkai** [comment]
An update will be pushed out tonight or tomorrow that'll fix this issue 🙂

**Comment by jetkai** [comment]
@alextatarinov update has been pushed to fix this bug.

The checker has been running for a few hours & seems to be stable. If it crashes overnight, I'll look into it. 

There are some formats missing that I'll sort out tomorrow, heading to sleep. 😊

(Updated backend from [https://github.com/jetkai/ProxyBuilder](https://github.com/jetkai/ProxyBuilder) -> [https://github.com/jetkai/proxy-builder-2](https://github.com/jetkai/proxy-builder-2))

**Comment by alextatarinov** [comment]
Great, thanks!
