### ISSUE TITLE
None of the Socks5 worked in LBRYcrd

### ISSUE THREAD

**Issue by juanpc2018** [jetkai/proxy-list#9]
None of the Socks5 worked in LBRYcrd

**Comment by jetkai** [comment]
I'll have a look into this, I believe the txt output file for SOCKS5 is sometimes pulling the HTTP port number.

Some proxies require multiple connection attempts to establish.

If you want to grab the info reliably you can use the .json file and sort by uptime/successful connections & pull the SOCKS4/5 port from the ports value.

**Comment by jetkai** [comment]
It's highly likely that the public proxies are blocked for that service. I'd recommend checking this with the LBRYcrd project or try using residential proxies.
